/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

//import javax.swing.JOptionPane;
import javax.swing.border.Border;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author campusLive Server
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        Border bordePersonalizado = BorderFactory.createLineBorder(Color.GREEN, 2); // Color y grosor
        txtNumero1.setBorder(bordePersonalizado);
        txtNumero2.setBorder(bordePersonalizado);
        txtResultado.setBorder(BorderFactory.createLineBorder(Color.DARK_GRAY, 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTexto1 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumero2 = new javax.swing.JTextField();
        btnSuma = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sumador");
        setBackground(new java.awt.Color(255, 250, 241));
        setResizable(false);

        lblTexto1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTexto1.setText("Numero 1");

        txtNumero1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumero1.setText("0");
        txtNumero1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumero1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero1FocusLost(evt);
            }
        });
        txtNumero1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumero1KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Numero 2");

        txtNumero2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtNumero2.setText("0");
        txtNumero2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumero2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumero2FocusLost(evt);
            }
        });
        txtNumero2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNumero2KeyPressed(evt);
            }
        });

        btnSuma.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSuma.setText("Sumar");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        txtResultado.setEditable(false);
        txtResultado.setBackground(new java.awt.Color(255, 255, 255));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtResultado.setText("0");
        txtResultado.setToolTipText("");
        txtResultado.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtResultadoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtResultadoFocusLost(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Resultado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(lblTexto1)
                    .addComponent(txtNumero1)
                    .addComponent(txtNumero2)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuma)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSuma)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTexto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        double num1 = Double.parseDouble(txtNumero1.getText());
        double num2 = Double.parseDouble(txtNumero2.getText());
        double res = num1 + num2;
        
        txtResultado.setText(String.valueOf(res));
    }//GEN-LAST:event_btnSumaActionPerformed

    public void focusGained(javax.swing.JTextField control) {
        control.setBorder(BorderFactory.createLineBorder(Color.BLUE, 2));
    }
    
    public void focusLost(javax.swing.JTextField control) {
        control.setBorder(BorderFactory.createLineBorder(Color.RED, 2));
    }
    
    private void txtNumero1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero1FocusGained
        focusGained(txtNumero1);
        txtNumero1.selectAll();
    }//GEN-LAST:event_txtNumero1FocusGained

    private void txtNumero2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero2FocusGained
        focusGained(txtNumero2);
        txtNumero2.selectAll();
    }//GEN-LAST:event_txtNumero2FocusGained

    private boolean esNumero (java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c) && c != '.' && c!=java.awt.event.KeyEvent.VK_BACK_SPACE) {
            return false;
        }
        
        return true;
    }
    
    private void txtNumero1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero1KeyPressed

        if (!esNumero(evt)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo puede ingrear números");
        }
    }//GEN-LAST:event_txtNumero1KeyPressed

    private void txtNumero2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumero2KeyPressed
        if (!esNumero(evt)) {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Solo puede ingrear números");
        }
    }//GEN-LAST:event_txtNumero2KeyPressed

    private void txtNumero1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero1FocusLost
        focusLost(txtNumero1);
    }//GEN-LAST:event_txtNumero1FocusLost

    private void txtNumero2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumero2FocusLost
        focusLost(txtNumero2);
    }//GEN-LAST:event_txtNumero2FocusLost

    private void txtResultadoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtResultadoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoFocusGained

    private void txtResultadoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtResultadoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblTexto1;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
